apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ruby-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-ruby-app
  template:
    metadata:
      labels:
        app: my-ruby-app
    spec:
      containers:
      - name: my-ruby-app
        image: viktoriiaa/my-ruby-app:latest
        env:
        - name: DATABASE_HOST
          value: "postgres"
        - name: DATABASE_USER
          value: "myuser"
        - name: DATABASE_PASSWORD
          value: "mypassword"
        - name: DATABASE_NAME
          value: "mydatabase"
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_USER
          value: "myuser"
        - name: POSTGRES_PASSWORD
          value: "mypassword"
        - name: POSTGRES_DB
          value: "mydatabase"
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      volumes:
      - name: postgres-storage
        emptyDir: {}
