default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV.fetch("DATABASE_USER", "myuser") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "mypassword") %>
  host: <%= ENV.fetch("DATABASE_HOST", "postgres") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  database: <%= ENV.fetch("DATABASE_NAME", "mydatabase") %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "mydatabase") %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "mydatabase") %>_test

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "mydatabase") %>
